name: Build and Deploy to Local Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Debugging step to confirm Dockerfile existence
    - name: Verify Dockerfile existence
      run: ls -l ./nginx-project

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.10.0
      with:
        context: ./nginx-project
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/demodockerrepo:1.19

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/demodockerrepo:1.19
        DOCKER_HOST: unix:///var/run/docker.sock

    - name: Delete Existing StatefulSet
      run: |
        kubectl delete statefulset nginx-statefulset --ignore-not-found=true
    - name: Apply StatefulSet YAML in Minikube
      run: |
        kubectl apply -f nginx-project/statefulset.yaml
        kubectl rollout status statefulset/nginx-statefulset --timeout=5m
        # Watch pod status until all pods are ready, with a 5-minute timeout.
        PODS_READY=$(kubectl get pods -l app=nginx-statefulset -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | wc -w)
        START_TIME=$(date +%s)
        while [ "$PODS_READY" -ne 3 ]; do
          CURRENT_TIME=$(date +%s)
          ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
          if [ "$ELAPSED_TIME" -ge 300 ]; then
            echo "Error: Pods are not ready after 5 minutes."
            kubectl describe statefulset nginx-statefulset
            kubectl get pods -l app=nginx-statefulset -o wide
            kubectl logs -l app=nginx-statefulset
            exit 1
          fi
          echo "Waiting for pods to be ready... Current ready pods: $PODS_READY"
          sleep 5
          PODS_READY=$(kubectl get pods -l app=nginx-statefulset -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | wc -w)
        done
        echo "All pods are ready."
    - name: Apply Nginx Service YAML in Minikube
      run: |
        kubectl apply -f nginx-project/nginx-service.yml
        kubectl get service nginx
    - name: Port-forward the service for access
      run: |
        kubectl port-forward svc/nginx 8080:80 &
        sleep 5 # Wait for port-forwarding to establish
        curl http://localhost:8080