name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t deepika2897/nginx-1.19:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push deepika2897/nginx-1.19:latest

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.30.0/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube version

    - name: Start Minikube with Docker driver
      run: |
        minikube start --driver=docker

    - name: Set up kubectl to work with Minikube
      run: |
        echo "export KUBEVERSION=$(minikube kubectl --version)" >> $GITHUB_ENV
        echo "export KUBEVERSION"        
        echo "export KUBE_CTX=default" >> $GITHUB_ENV
        echo "export KUBE_CTX" 
        echo "export MINIKUBE_PROFILE=default" >> $GITHUB_ENV
        echo "export MINIKUBE_PROFILE"

    - name: Apply StatefulSet YAML in Minikube
      run: |
        kubectl apply -f statefulset.yaml
        kubectl rollout status statefulset/nginx-statefulset

    - name: Apply Nginx Service YAML in Minikube
      run: |
        kubectl apply -f nginx-service.yaml
        kubectl rollout status service/nginx

    - name: Port-forward the service for access
      run: |
        kubectl port-forward svc/nginx 8080:80 &
        sleep 5 # Wait for port-forwarding to establish
        curl http://localhost:8080
