name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the `main` branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t deepika2897/nginx-1.19:latest .

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push deepika2897/nginx-1.19:latest

    # Step 6: Set up Minikube
    - name: Set up Minikube
      uses: medikoo/action-minikube@v2
      with:
        minikube_version: 'v1.30.0'

    # Step 7: Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker

    # Step 8: Apply Kubernetes StatefulSet YAML in Minikube
    - name: Apply StatefulSet in Minikube
      run: |
        kubectl apply -f statefulset.yaml
        kubectl rollout status statefulset/nginx-statefulset

    # Step 9: Expose the service and get the URL
    - name: Expose Service and Get URL
      run: |
        minikube service nginx --url
